### ISSUE TITLE
Type assertion error in dynamo

### ISSUE THREAD

**Issue by phipsgabler** [MikeInnes/IRTools.jl#14]
This happens in v0.2.2, as soon as I do anything else than the trivial `test(a...) = IR(a...)`:

```
julia> IRTools.@dynamo test4(a...) = (ir = IRTools.IR(); push!(ir, IRTools.xcall(Main, :println, "hi")); ir)

julia> test4(identity, 1)
ERROR: TypeError: in dynamo, in typeassert, expected IRTools.Meta, got Nothing
Stacktrace:
 [1] dynamo(::Function, ::Type, ::Vararg{Type,N} where N) at /home/philipp/.julia/packages/IRTools/y0Ot8/src/reflection/dynamo.jl:7
 [2] #s14#7(::Any, ::Any) at /home/philipp/.julia/packages/IRTools/y0Ot8/src/reflection/dynamo.jl:16
 [3] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:506
 [4] top-level scope at none:0
```

It comes from [this assertion](https://github.com/MikeInnes/IRTools.jl/blob/v0.2.2/src/reflection/dynamo.jl#L7), which is more specific than the [actual field type](https://github.com/MikeInnes/IRTools.jl/blob/v0.2.2/src/ir/ir.jl#L67) in the definition of `IR`, as far as I can see. (No idea what it should do, though.)

**Comment by MikeInnes** [comment]
Basically, what's happening here is that when you do `IR(a...)`, the IR has some metadata that attaches it to a given method, which we use for internal runtime stuff. But if you create an IR from scratch there is no metadata, which currently isn't supported

The easy fix is to do `ir = empty(IR(a...))` which should behave how you want.

In future we could add support for from-scratch IR fragments, but there are some design issues there so it'd be good for it to be driven by a use case. Obviously in any case it'd be nice to improve the error messages and add some docs on this.

**Comment by phipsgabler** [comment]
I already suspected some method metadata thing, thanks.  Unfortunately, the following still does not work:

```
julia> IRTools.@dynamo test4(a...) = (ir = empty(IRTools.IR(a...)); push!(ir, IRTools.xcall(Main, :println, "hi")); ir)

julia> test4(identity, 1)
ERROR: TypeError: in dynamo, in typeassert, expected IRTools.Meta, got Nothing
Stacktrace:
 [1] dynamo(::Function, ::Type, ::Vararg{Type,N} where N) at /home/philipp/.julia/packages/IRTools/y0Ot8/src/reflection/dynamo.jl:7
 [2] #s14#7(::Any, ::Any) at /home/philipp/.julia/packages/IRTools/y0Ot8/src/reflection/dynamo.jl:16
 [3] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:506
 [4] top-level scope at none:0
```

Did you mean something else? 

My use case is that I insert tracking statements after every statement of a given method (and some more places), so I thought it to be easier to build up the new IR from an empty start by `push!`ing (also, just following the docs). Otherwise I'd have to call `insertafter!` a linear number of times and do more bookkeeping.

If you could point me to some place where I can see how to "manually" transfer or build bup that metadata, I could try to find out how to do that on my own, but until now, I just never discovered a starting point -- e.g., Zygote uses IRTools, but I couldn't find the place where they actually construct their IR stuff.  That should be possible "by hand" without using `@dynamo`, I suppose?

Since I think that I'm going to end up using IRTools anyway, I'll probably try to improve the docs a bit, as soon as I have a good enough understanding of what I'm doing.

**Comment by phipsgabler** [comment]
Ok, I just found the `reverse.jl` example, that's probably quite similar to what I'm doing.  Can you point me to an explanation of what this `Pipe` system does?

**Comment by MikeInnes** [comment]
Is that on master? It's possible that `empty` changed relatively recently.

But yeah, for that case you definitely want `Pipe`, see [here](https://mikeinnes.github.io/IRTools.jl/latest/reference/#IRTools.Pipe).

**Comment by phipsgabler** [comment]
No, that's on v0.2.2.  And [there](https://github.com/MikeInnes/IRTools.jl/blob/v0.2.2/src/ir/ir.jl#L289) you don't copy the metadata, as you do on master.  I'll just switch branches for now, then.  Any speculation when the next release will come out?

And thanks for the pointer to the newer docs, much appreciated!

**Comment by phipsgabler** [comment]
An updated test example works on master, if one first inserts the missing `return` at the end:

```
julia> IRTools.@dynamo function test8(a...) 
           @show a
           @show IRTools.IR(a...).meta
           ir = empty(IRTools.IR(a...))
           @show ir.meta
           push!(ir, IRTools.xcall(Main, :println, "hi"))
           IRTools.return!(ir, nothing)
           return ir
       end

julia> test8(identity, 1)
a = (typeof(identity), Int64)
(IRTools.IR(a...)).meta = Metadata for identity(x) in Base at operators.jl:475
ir.meta = Metadata for identity(x) in Base at operators.jl:475
hi
```

(Without the `return!` it segfaults, but that's not IRTools fault.)

**Comment by MikeInnes** [comment]
Great. I'm hoping to cut a new release with all the new docs/examples fairly soon.

Feel free to open issues for crashes like that; it'd be nice if we could protect against that kind of thing by default, where possible.
