### ISSUE TITLE
pushfirst! missing for Pipe

### ISSUE THREAD

**Issue by phipsgabler** [MikeInnes/IRTools.jl#16]
There should be an equivalent to the method of IR, pushing a statement at the front of the pipe.  Currently I use

```julia
function pushfirst!(p::IRTools.Pipe, x)
    first_v, first_stmt = first(p)
    IRTools.insert!(p, first_v, x)
end
```

Is the following modification of `push!` correct, or is there even something simpler?

```julia
function pushfirst!(p::IRTools.Pipe, x)
    tmp = IRTools.var!(p)
    IRTools.substitute!(p, tmp, IRTools.pushfirst!(p.to, prewalk(IRTools.substitute(p), x)))
    return tmp
end
```

**Comment by MikeInnes** [comment]
Note that this wouldn't be more efficient on pipes, but it doesn't do any harm to add it. That looks right to me so would be great to have as a PR.
