### ISSUE TITLE
`block!(ir, i)` wrongly relabels all other branches

### ISSUE THREAD

**Issue by phipsgabler** [MikeInnes/IRTools.jl#26]
Because reasons (tracking, again), I want to unify all returns in my IR into one single one.  My idea was to do this by adding a new block at the end, and replace all other returns by an unconditional branch to this.  However, it turns out that this completely destroys the jump targets of all other branching instructions, as you can see here:

```
julia> function test2(x)
           if x < 0
               return x + 1
           else
               return x - 1
           end
       end
test2 (generic function with 1 method)

julia> ir = @code_ir test2(2)
1: (%1, %2)
  %3 = %2 < 0
  br 3 unless %3
2:
  %4 = %2 + 1
  return %4
3:
  %5 = %2 - 1
  return %5

julia> function single_return(ir)
           new_ir = IRTools.empty(ir)
           
           return_block = IRTools.block!(new_ir)
           return_value = IRTools.argument!(return_block, insert = false)
           IRTools.return!(return_block, return_value)
           
           for (i, old_block) in enumerate(IRTools.blocks(ir))
               new_block = (i == 1) ? IRTools.block(new_ir, 1) : IRTools.block!(new_ir, i)

               for (v, stmt) in old_block
                   push!(new_block, stmt)
               end

               for branch in IRTools.branches(old_block)
                   if IRTools.isreturn(branch)
                       IRTools.branch!(new_block, return_block, branch.args...)
                   else
                       IRTools.branch!(new_block, branch.block, branch.args...; unless = branch.condition)
                   end
               end
               @show new_ir
           end

           return new_ir
       end
single_return (generic function with 1 method)

julia> single_return(ir)
new_ir = 1:
  %2 = %2 < 0
  br 3 unless %3
2: (%1)
  return %1

new_ir = 1:
  %2 = %2 < 0
  br 4 unless %3
2:
  %3 = %2 + 1
  br 2 (%4)
3: (%1)
  return %1

new_ir = 1:
  %2 = %2 < 0
  br 5 unless %3
2:
  %3 = %2 + 1
  br 3 (%4)
3:
  %4 = %2 - 1
  br 2 (%5)
4: (%1)
  return %1

1:
  %2 = %2 < 0
  br 5 unless %3
2:
  %3 = %2 + 1
  br 3 (%4)
3:
  %4 = %2 - 1
  br 2 (%5)
4: (%1)
  return %1

```

Looking at the implementation of [`block!](https://github.com/MikeInnes/IRTools.jl/blob/fc0f7fae854b95614e1df5591dc245652b4d2ec1/src/ir/ir.jl#L115), I can see that it does some extra "intelligence" to relabel all existing branches, which I assume to be the reason for this.

Is there a better alternative, or should there just be an extra argument like `argument!`s `insert = false` to prevent this?

(I'm not using `Pipe` anymore precisely because of things like this -- that I don't have enough control over branching.)

**Comment by MikeInnes** [comment]
You probably want to look at / just use [`merge_returns`](https://github.com/MikeInnes/IRTools.jl/blob/master/src/passes/passes.jl#L82-L92), which is a fair bit simpler for just modifying an existing piece of IR.

`block!` is expecting to be used that way – modifying IR that already exists. If you really want to build a new IR fragment with a different CFG, it's best to do it by appending, and then this rewriting won't happen. In this case you know the return block ID ahead of time anyway, so it'd just be a case of appending that block last, rather than first.

**Comment by phipsgabler** [comment]
And again, something which I implement already exists... :)

You mean something like the following, right?

```
function merge_returns(ir)
    new_ir = IRTools.empty(ir)
    L = length(ir.blocks)

    for (i, old_block) in enumerate(IRTools.blocks(ir))
        new_block = (i == 1) ? IRTools.block(new_ir, 1) : IRTools.block!(new_ir, i)

        for (v, stmt) in old_block
            push!(new_block, stmt)
        end

        for branch in IRTools.branches(old_block)
            if IRTools.isreturn(branch)
                IRTools.branch!(new_block, L + 1, branch.args...)
            else
                IRTools.branch!(new_block, branch.block, branch.args...; unless = branch.condition)
            end
        end
        @show new_ir
    end
	
    return_block = IRTools.block!(new_ir)
    return_value = IRTools.argument!(return_block, insert = false)
    IRTools.return!(return_block, return_value)

    return new_ir
end
```

**Comment by MikeInnes** [comment]
Yeah, exactly.
