### ISSUE TITLE
How @code_ir be converted to lower IR or runnable IR  and how can I get @code_lowered IR with script code not with REPL 

### ISSUE THREAD

**Issue by agdkyang** [MikeInnes/IRTools.jl#66]
how @code_ir be converted to lower IR such as @code_typed  or runnable IR

**Comment by MikeInnes** [comment]
As mentioned in the readme, you can use `IRTools.func` to get a runnable Julia function from IR. You can then use `@code_lowered` or `@code_typed` on that function.

**Comment by agdkyang** [comment]
> As mentioned in the readme, you can use `IRTools.func` to get a runnable Julia function from IR. You can then use `@code_lowered` or `@code_typed` on that function.
