### ISSUE TITLE
Not defined in master branch/v1.2

### ISSUE THREAD

**Issue by Roger-luo** [MikeInnes/IRTools.jl#7]
https://github.com/MikeInnes/IRTools.jl/blob/c39410793a9b79cb5ff6e486df0ffff56d2adcb2/src/reflection/reflection.jl#L23

I guess this is changed due to https://github.com/JuliaLang/julia/pull/31191 ?

**Comment by tpapp** [comment]
I think that `Core.Compiler.specialize_method` should be a drop-in replacement for `code_for_method`.

**Comment by MikeInnes** [comment]
Any chance of trying it in a PR? Would be great to add Julia nightly to travis testing as well.

**Comment by tpapp** [comment]
Sure, will do one in a few minutes.

**Comment by tpapp** [comment]
I take that back: apparently the changes were more complex than this (omitting world age, other small changes to the reflection API) so I think this should be done someone who knows these better.

**Comment by MikeInnes** [comment]
Ok, fixed on master.
